### ISSUE TITLE
Implement a test infrastructure

### ISSUE THREAD

**Issue by ferrarimarco** [iknite/cookiecutter-ansible-role#6]
Currently generated roles do not include any test facility.

I'll provide a pull request that implements testing with [Test-Kitchen](https://github.com/test-kitchen/test-kitchen) configured with the [kitchen-docker](https://github.com/test-kitchen/kitchen-docker) driver,
and [kitchen-inspec](https://github.com/chef/kitchen-inspec).

Let's talk about this :)

**Comment by pgporada** [comment]
I personally use this `Gemfile` and this `.kitchen.yml` to test my ansible roles.

`Gemfile`
```
source "https://rubygems.org"

gem "test-kitchen"
gem "kitchen-vagrant"
gem "vagrant-wrapper"
gem "kitchen-ansible"
gem "busser-bats"
gem "kitchen-sync"
```

`.kitchen.yml`
```yml
---
driver:
  name: vagrant
  use_sudo: false
  forward_agent: true

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_ansible_repo: true
  ansible_yum_repo: epel
  require_ansible_omnibus: false
  ansible_verbosity: 2
  ansible_verbose: true
  ansible_diff: true
  require_chef_for_busser: true
  update_package_repos: false
  requirements_path: test/requirements.yml
  ssh_known_hosts:
    - bitbucket.org

platforms:
  - name: centos-7
    driver:
      box: centos/7
      provision: true
      vagrantfiles:
        - .vagrant.rb
      network:
        - ["private_network", {ip: "192.168.33.102"}]

suites:
  - name: default

transport:
  forward_agent: true
  name: rsync
...
```

`.vagrant.rb`
```
Vagrant.configure(2) do |config|
    config.vm.provision "shell", inline: "sudo systemctl restart network.service || true", run: "always"
    config.vm.provision "shell", inline: <<-SHELL
        sudo yum install -y epel-release git vim telnet net-tools rsync
        sudo yum update -y epel-release
        sudo yum install -y ansible
    SHELL
end
```

Instead of inspec, I use [BATS](https://github.com/sstephenson/bats) because $REASONS.

**Comment by pgporada** [comment]
@ferrarimarco Do you use a tool such as `yamllint`?

If not, here is my config
```
---
extends: default

rules:
  line-length:
    max: 80
    level: warning
  document-start:
    present: true
  document-end:
    present: true
  key-duplicates: enable
  trailing-spaces: enable
  new-line-at-end-of-file: disable
  hyphens:
    max-spaces-after: 1
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
...
```

I use it with this alias
```
alias yams='find . -type f -name "*.yml*" | sed "s|\./||g" | egrep -v "(\.kitchen/|\[warning\]|\.molecule/)" | xargs yamllint -f parsable'
```
